#!/bin/bash

export DESKTOP_CORE_NAME="docker"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v4.24.0
export DESKTOP_CORE_MD5SUM=5eeac1c71caff672e99d3f4180f09233
export DESKTOP_CORE_ORG="docker"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://desktop.docker.com"
