#!/bin/bash

install() {
  # prepare vars
  local name="$DESKTOP_CORE_NAME"

  log::info "[$(timestamp)][desktop][$name] preparing ..."

  # get system os/arch
  local os="$DESKTOP_OS"
  local arch="$DESKTOP_OS_ARCH"
  local kernel="$DESKTOP_OS_KERNEL"
  local platform="$DESKTOP_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$DESKTOP_USER_BIN_DIR"
  local cache_dir="$DESKTOP_CACHE_DIR"
  local tmp_dir="$DESKTOP_TMP_DIR"

  #
  case $platform in
  darwin) ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # case $arch in
  # arm64) ;;

  # amd64)
  #   arch="x86_64"
  #   ;;
  # *)
  #   log::error "[$(timestamp)] unsupport arch: $arch"
  #   return 1
  #   ;;
  # esac
  # #

  # files
  local cache_file="$cache_dir/$DESKTOP_CORE_VERSION.dmg"
  # local source_bin_file="./$name"

  # prepare context
  log::info "[$(timestamp)][desktop][$name] context: $tmp_dir ..."
  cd $tmp_dir

  local is_cached="false"
  if [ -f "$cache_file" ]; then
    local cache_file_checksum=$(os::sha256 $cache_file)
    local cache_file_checksum_expect=""

    case $DESKTOP_CORE_VERSION in
    v4.24.0)
      case $arch in
      arm64)
        cache_file_checksum_expect="048e28f9834179008d4728ad59171584b793a76f5d2d52c13b577d1bbb2f699b"
        ;;
      amd64)
        cache_file_checksum_expect="67ba11934540270ad37ede8c4d6b3b73ef393690ee2aebca04b6591d22ffe4c5"
        ;;
      esac
      ;;
    esac

    if [ "$cache_file_checksum" = "$cache_file_checksum_expect" ]; then
      is_cached="true"
    fi
  fi

  if [ "$is_cached" != "true" ]; then
    # example:
    #   https://desktop.docker.com/mac/main/arm64/Docker.dmg
    #   https://desktop.docker.com/mac/main/amd64/Docker.dmg
    # generate url
    local url="${DESKTOP_CORE_RELEASE_DOWNLOAD}/mac/main/${arch}/Docker.dmg"
    log::debug "[$(timestamp)][desktop][$name][$kernel][$arch] url: $url, file: ${cache_file}, tmp_dir: $tmp_dir"

    # download
    log::info "[$(timestamp)][desktop][$name] downloading from $url ..."
    os::download $cache_file $url
  else
    log::info "[$(timestamp)][desktop][$name] found cache at $cache_file ..."
  fi

  # install
  log::info "[$(timestamp)][desktop][$name] installing $cache_file ..."
  install::dmg $cache_file ${name} Docker.app "/Volumes/Docker"

  # clean
  log::info "[$(timestamp)][desktop][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
